module Tarefa6_2022li1g013_Spec where

import LI12223
import Tarefa6_2022li1g013
import Test.HUnit

testsT6 :: Test
testsT6 = test ["criarmapa" ~: [(Rio (-1),[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio 2,[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Estrada (-2),[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum]),(Estrada 2,[Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Rio (-2),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Rio 2,[Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum]),(Estrada (-2),[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Carro,Nenhum,Nenhum,Carro]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])] ~=? criarmapa 11 15 [] 46 0,
                "criarmapa" ~: [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Rio (-1),[Tronco,Nenhum,Nenhum,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Rio 2,[Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum]),(Estrada (-2),[Carro,Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada 2,[Nenhum,Nenhum,Carro,Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum]),(Estrada 2,[Nenhum,Nenhum,Nenhum,Carro,Nenhum,Carro,Nenhum,Nenhum,Carro,Nenhum,Nenhum]),(Rio (-2),[Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum]),(Rio (-1),[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Tronco,Nenhum]),(Rio 2,[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Tronco,Nenhum]),(Estrada (-2),[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Carro]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])] ~=? criarmapa 11 15 [] 67 0,
                "criarmapa" ~: [(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada (-2),[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada 2,[Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada (-2),[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum]),(Rio 1,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Tronco,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])] ~=? criarmapa 11 15 [] 1 0,
                "obstaculototile" ~: [RioT,Tronco1T,Tronco1T,RioT,Tronco1T] ~=? obstaculototile (Rio 1,[Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                "obstaculototile" ~: [RioT,Tronco2T,Tronco2T,RioT,Tronco2T] ~=? obstaculototile (Rio (-1),[Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                "obstaculototile" ~: [EstradaT,Carro1T,Carro1T,EstradaT,Carro1T] ~=? obstaculototile (Estrada 2,[Nenhum,Carro,Carro,Nenhum,Carro]),
                "obstaculototile" ~: [EstradaT,Carro2T,Carro2T,EstradaT,Carro2T] ~=? obstaculototile (Estrada (-2),[Nenhum,Carro,Carro,Nenhum,Carro]),
                "obstaculototile" ~: [RelvaT,ArvoreT,ArvoreT,RelvaT,ArvoreT] ~=? obstaculototile (Relva,[Nenhum,Arvore,Arvore,Nenhum,Arvore]),
                "mapatotilelist" ~: [[EstradaT,Carro2T,EstradaT,EstradaT],[Tronco2T,Tronco2T,RioT,Tronco2T],[RelvaT,RelvaT,ArvoreT,ArvoreT]] ~=? mapatotilelist [(Estrada (-2),[Nenhum,Carro,Nenhum,Nenhum]),(Rio (-2),[Tronco,Tronco,Nenhum,Tronco]),(Relva,[Nenhum,Nenhum,Arvore,Arvore])],
                "mapatotilelist" ~: [[RioT,Tronco1T,Tronco1T,RioT],[EstradaT,Carro1T,EstradaT,Carro1T],[EstradaT,Carro2T,Carro2T,Carro2T],[EstradaT,Carro1T,EstradaT,EstradaT],[ArvoreT,RelvaT,ArvoreT,ArvoreT],[EstradaT,Carro1T,Carro1T,EstradaT],[Carro2T,EstradaT,EstradaT,EstradaT]] ~=? mapatotilelist [(Rio 3,[Nenhum,Tronco,Tronco,Nenhum]),(Estrada 4,[Nenhum,Carro,Nenhum,Carro]),(Estrada (-1),[Nenhum,Carro,Carro,Carro]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Arvore,Arvore]),(Estrada 5,[Nenhum,Carro,Carro,Nenhum]),(Estrada (-2),[Carro,Nenhum,Nenhum,Nenhum])]
               ]